=== eXpansionPluginPack/eXpansion2/src/eXpansion/Framework/MlComposeBundle/Resources/config/page-compose.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="block" type="blockType" ></xs:element>
    <xs:element name="argument" type="argumentType" ></xs:element>

    <!-- List of types available -->
    <xs:complexType name="argumentType" mixed="true">
        <xs:attribute name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="args" mixed="true">
        <xs:complexContent>
            <xs:extension base="argumentType">
                <xs:sequence>
                    <xs:element name="arg" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="action" mixed="true">
        <xs:complexContent>
            <xs:extension base="argumentType">
                <xs:sequence>
                    <xs:element name="method" minOccurs="1" maxOccurs="1" type="xs:string"/>
                    <xs:element name="service" minOccurs="0" maxOccurs="1" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="expr">
        <xs:complexContent>
            <xs:extension base="argumentType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="blockType">
        <xs:sequence>
            <xs:element ref="argument" maxOccurs="unbounded" minOccurs="0" />
            <xs:element ref="block" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>

        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="component" use="optional"/>
        <xs:attribute type="xs:string" name="extends" use="optional"/>
        <xs:attribute type="xs:string" name="alias" use="optional"/>
    </xs:complexType>
</xs:schema>

=== eXpansionPluginPack/eXpansion2/src/eXpansion/Framework/Core/Resources/config/ml-compose/window.help.xml
<?xml version="1.0"?>
<block id="window.exp.core.help" extends="base.window" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/src/eXpansion/Framework/MlComposeBundle/Resources/config/page-compose.xsd">

     <block component="Frame" id="window.exp.core.help.content" alias="content">

         <!-- TODO this won't work as we don't yet have the base grid element. But an idea on how to define one !!-->
        <block extends="base.exp.grid" id="window.exp.core.help.grid">
            <argument name="width" xsi:type="expr">factory.getWidth()-2</argument>
            <argument name="height" xsi:type="expr">factory.getHeight()-2</argument>
            <argument name="x">1</argument>
            <argument name="y">-1</argument>


            <argument name="data-source" xsi:type="service">@MySuperService</argument>
            <argument name="layout">table</argument>

            <!-- List the columns, this is not necessary for layout "grid" -->
            <argument name="columns" xsi:type="args">
                <arg name="command">expansion_core.windows.chat_commands.column_command</arg>
                <arg name="description">expansion_core.windows.chat_commands.column_description</arg>
                <arg name="help">expansion_core.windows.chat_commands.help</arg>
            </argument>
            <argument name="comumn-widths" xsi:type="args">
                <arg name="command">25</arg>
                <arg name="description">70</arg>
                <arg name="help">10</arg>
            </argument>

            <!-- How will the columns be displayed -->
            <block extends="base.exp.grid.text" id="window.exp.core.help.grid.command" alias="column-command"/>
            <block extends="base.exp.grid.text" id="window.exp.core.help.grid.description" alias="column-description"/>
            <block extends="base.exp.grid.action" id="window.exp.core.help.grid.help" alias="column-help">
                <argument name="service" xsi:type="service">@MySuperService</argument>
                <argument name="method" xsi:type="service">showExtendedHelp</argument>
            </block>
        </block>
    </block>
</block>

=== eXpansionPluginPack/eXpansion2/src/eXpansion/Framework/MlComposeBundle/Resources/config/ml-compose/base.window.xml
<?xml version="1.0"?>
<block component="Frame" id="base.window" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../page-compose.xsd">
    <argument name="x">-2</argument>
    <argument name="y">7.5</argument>
    <argument name="width" xsi:type="expr">factory.getWidth()+4</argument>
    <argument name="height" xsi:type="expr">factory.getHeight()+7.5</argument>

    <!-- Definint the title bar -->
    <block component="Label" id="base.window.title_label">
        <argument name="x">3</argument>
        <argument name="y">1</argument>
        <argument name="width" xsi:type="expr">factory.getWidth()-20</argument>
        <argument name="vAlign">CENTER2</argument>
        <argument name="hAlign">LEFT</argument>
        <argument name="id">TitleText</argument>
        <argument name="textFont">RajdhaniMono</argument>
        <argument name="textSize">2</argument>
        <argument name="textId" xsi:type="expr">factory.getName()</argument>
    </block>

    <block component="Quad" id="base.window.separator">
        <argument name="x">0</argument>
        <argument name="y">-5.5</argument>
        <argument name="width" xsi:type="expr">factory.getWidth()-20</argument>
        <argument name="height">0.33</argument>
        <argument name="backgroundColor">fff</argument>
    </block>
    <block component="Quad" id="base.window.separator_bis">
        <argument name="x">0</argument>
        <argument name="y">-5.5</argument>
        <argument name="width" xsi:type="expr">factory.getWidth()/4</argument>
        <argument name="height">0.5</argument>
        <argument name="backgroundColor">fff</argument>
    </block>

    <block component="Quad" id="base.window.title_bar">
        <argument name="width" xsi:type="expr">factory.getWidth()-9.5</argument>
        <argument name="height">5.5</argument>
        <argument name="backgroundColor">000e</argument>
        <argument name="scriptEvents">1</argument>
    </block>

    <block component="Label" id="base.window.close_label">
        <argument name="x" xsi:type="expr">factory.getWidth()-5</argument>
        <argument name="y" xsi:type="expr">3</argument>
        <argument name="width">9.5</argument>
        <argument name="height">5.5</argument>
        <argument name="text">âœ–</argument>
        <argument name="textColor">fff</argument>
        <argument name="textSize">2</argument>
        <argument name="textFont">OswaldMono</argument>
        <argument name="scriptEvents">1</argument>
        <argument name="areaColor">000e</argument>
        <argument name="areaFocusColor">f22</argument>
        <argument name="action" xsi:type="action">
            <method>closeCallback</method>
        </argument>
    </block>

    <!-- Body -->
    <block component="Quad" id="base.window.bg1">
        <argument name="y">-5.5</argument>
        <argument name="width" xsi:type="expr">factory.getWidth()</argument>
        <argument name="height" xsi:type="expr">factory.getHeight()-5.5</argument>
        <argument name="backgroundColor">222</argument>
        <argument name="opacity">0.8</argument>
    </block>
    <block component="Quad" id="base.window.bg2">
        <argument name="id">WindowBg</argument>
        <argument name="y">-5.5</argument>
        <argument name="width" xsi:type="expr">factory.getWidth()</argument>
        <argument name="height" xsi:type="expr">factory.getHeight()-5.5</argument>
        <argument name="style" xsi:type="args"><arg>Bgs1</arg><arg>BgDialogBlur</arg></argument>
        <argument name="opacity">0.8</argument>
    </block>
    <block component="Quad" id="base.window.bg3">
        <argument name="x">-5.5</argument>
        <argument name="y">5.5</argument>
        <argument name="width" xsi:type="expr">factory.getWidth()+10</argument>
        <argument name="height" xsi:type="expr">factory.getHeight()-10</argument>
        <argument name="style" xsi:type="args"><arg>Bgs1InRace</arg><arg>BgButtonShadow</arg></argument>
        <argument name="opacity">0.8</argument>
    </block>

    <block component="Frame" id="base.window.content" alias="content">
        <argument name="x">0</argument>
        <argument name="y">0</argument>
        <argument name="width" xsi:type="expr">factory.getWidth()</argument>
        <argument name="height" xsi:type="expr">factory.getHeight()</argument>

        <!-- Content needs to be added here" -->
    </block>
</block>
